### ISSUE TITLE
Huggingface checkpoints

### ISSUE THREAD

**Issue by fteufel** [instadeepai/nucleotide-transformer#14]
Hi,

i've just seen that you made weights available at https://huggingface.co/InstaDeepAI .

As so far they're not documented anywhere, could you confirm that those are good to use?

Thanks!

**Comment by ranzenTom** [comment]
Hi fteufel,

We are working on it with HuggingFace teams right now. For now, I would recommend using the code in this repository but the code on HuggingFace should be fully ready to be used in a few days. Right now the uploaded models are correct but the tokenizer is still missing and we are working on it.

**Comment by ranzenTom** [comment]
The 4 checkpoints and 2 pre-training datasets are now available on Huggingface, you can see the list [here](https://huggingface.co/InstaDeepAI)!

You can use them using standard classes like AutoTokenizer,AutoModelForMaskedLM or AutoModelForSequenceClassification. We fixed a couple of issues related to this in recent PRs, so please update transformers to the latest version on main with pip install --upgrade git+https://github.com/huggingface/transformers.git before trying to use them.

PyTorch only for now, but we expect TensorFlow versions to be available in a couple of days!
