### ISSUE TITLE
2 sequences as input

### ISSUE THREAD

**Issue by hhy-joseph** [instadeepai/nucleotide-transformer#16]
Thank you so much for sharing the pre-trained model! I am eager to explore its capabilities in some specific tasks and would like to fine-tune the model accordingly. Is it possible to input 2 sequences as input to perform a classification task?
Thank you!

**Comment by dallatt** [comment]
Hello @hhy-joseph , 

Sorry for the late reply, we have never tested this setting until now.

I guess the two most straightforward ways are:
1. Adapt the tokenizer to concatenate the two sequences with a `<sep>` token 
2. Pass each sequence in the encoder and add/concatenate them before feeding the resulting embedding to the classification head.

Hope this helps, 
Best regards,
Hugo
