### ISSUE TITLE
model size mismatch 

### ISSUE THREAD

**Issue by Azai-yx** [instadeepai/nucleotide-transformer#24]
hello there, 

recently I trying to load 'InstaDeepAI/nucleotide-transformer-v2-50m-multi-species' weight to generate sequence embbedings. However i met this issue while I trying to run the snippet code. the error shows blow:

RuntimeError: Error(s) in loading state_dict for EsmForMaskedLM:
	size mismatch for esm.encoder.layer.0.intermediate.dense.weight: copying a param with shape torch.Size([4096, 512]) from checkpoint, the shape in current model is torch.Size([2048, 512]).
	size mismatch for esm.encoder.layer.1.intermediate.dense.weight: copying a param with shape torch.Size([4096, 512]) from checkpoint, the shape in current model is torch.Size([2048, 512]).
	size mismatch for esm.encoder.layer.2.intermediate.dense.weight: copying a param with shape torch.Size([4096, 512]) from checkpoint, the shape in current model is torch.Size([2048, 512]).
	size mismatch for esm.encoder.layer.3.intermediate.dense.weight: copying a param with shape torch.Size([4096, 512]) from checkpoint, the shape in current model is torch.Size([2048, 512]).
	size mismatch for esm.encoder.layer.4.intermediate.dense.weight: copying a param with shape torch.Size([4096, 512]) from checkpoint, the shape in current model is torch.Size([2048, 512]).
	size mismatch for esm.encoder.layer.5.intermediate.dense.weight: copying a param with shape torch.Size([4096, 512]) from checkpoint, the shape in current model is torch.Size([2048, 512]).
	size mismatch for esm.encoder.layer.6.intermediate.dense.weight: copying a param with shape torch.Size([4096, 512]) from checkpoint, the shape in current model is torch.Size([2048, 512]).
	size mismatch for esm.encoder.layer.7.intermediate.dense.weight: copying a param with shape torch.Size([4096, 512]) from checkpoint, the shape in current model is torch.Size([2048, 512]).
	size mismatch for esm.encoder.layer.8.intermediate.dense.weight: copying a param with shape torch.Size([4096, 512]) from checkpoint, the shape in current model is torch.Size([2048, 512]).
	size mismatch for esm.encoder.layer.9.intermediate.dense.weight: copying a param with shape torch.Size([4096, 512]) from checkpoint, the shape in current model is torch.Size([2048, 512]).
	size mismatch for esm.encoder.layer.10.intermediate.dense.weight: copying a param with shape torch.Size([4096, 512]) from checkpoint, the shape in current model is torch.Size([2048, 512]).
	size mismatch for esm.encoder.layer.11.intermediate.dense.weight: copying a param with shape torch.Size([4096, 512]) from checkpoint, the shape in current model is torch.Size([2048, 512]).
	size mismatch for esm.encoder.layer.12.intermediate.dense.weight: copying a param with shape torch.Size([4096, 512]) from checkpoint, the shape in current model is torch.Size([2048, 512]).
	size mismatch for esm.encoder.layer.13.intermediate.dense.weight: copying a param with shape torch.Size([4096, 512]) from checkpoint, the shape in current model is torch.Size([2048, 512]).
	size mismatch for esm.encoder.layer.14.intermediate.dense.weight: copying a param with shape torch.Size([4096, 512]) from checkpoint, the shape in current model is torch.Size([2048, 512]).
	size mismatch for esm.encoder.layer.15.intermediate.dense.weight: copying a param with shape torch.Size([4096, 512]) from checkpoint, the shape in current model is torch.Size([2048, 512]).
	size mismatch for esm.encoder.layer.16.intermediate.dense.weight: copying a param with shape torch.Size([4096, 512]) from checkpoint, the shape in current model is torch.Size([2048, 512]).
	size mismatch for esm.encoder.layer.17.intermediate.dense.weight: copying a param with shape torch.Size([4096, 512]) from checkpoint, the shape in current model is torch.Size([2048, 512]).
	size mismatch for esm.encoder.layer.18.intermediate.dense.weight: copying a param with shape torch.Size([4096, 512]) from checkpoint, the shape in current model is torch.Size([2048, 512]).
	size mismatch for esm.encoder.layer.19.intermediate.dense.weight: copying a param with shape torch.Size([4096, 512]) from checkpoint, the shape in current model is torch.Size([2048, 512]).
	size mismatch for esm.encoder.layer.20.intermediate.dense.weight: copying a param with shape torch.Size([4096, 512]) from checkpoint, the shape in current model is torch.Size([2048, 512]).
	size mismatch for esm.encoder.layer.21.intermediate.dense.weight: copying a param with shape torch.Size([4096, 512]) from checkpoint, the shape in current model is torch.Size([2048, 512]).
	You may consider adding `ignore_mismatched_sizes=True` in the model `from_pretrained` method.

the model weight and its config were download from https://huggingface.co/InstaDeepAI/nucleotide-transformer-v2-100m-multi-species/tree/main, and were used in a offline mode.

**Comment by dallatt** [comment]
Hello, 
I recommend you execute the code snippet provided in the model card, where the argument `trust_remote_code=True` is added. This is necessary because the config and model file were written by someone other than HuggingFace (us).

I went ahead and added an extra step so that when not providing this argument, the architecture does not revert to standard ESM architecture (which is where the shape mismatch come from).

**Comment by Azai-yx** [comment]
it perfectly works， thanks!
