### ISSUE TITLE
hyenadna evaluation

### ISSUE THREAD

**Issue by wawpaopao** [instadeepai/nucleotide-transformer#25]
Thanks your great work!
i want to ask how do you use hyenadna to finetuning,(1)just like their github,python -m train wandb=null experiment=hg38/nucleotide_transformer dataset_name=enhancer dataset.max_length=500 model.layer.l_max=1026
or download the weights and use huggingface trainer like their colab?

**Comment by dallatt** [comment]
Hello, 

Sorry for the late reply!

We followed the procedure given in the github to run all experiments!

Best regards,
Hugo
