### ISSUE TITLE
Performance on RNA sequences

### ISSUE THREAD

**Issue by vuhongai** [instadeepai/nucleotide-transformer#27]
Thank you for outsourcing these amazing models. Since the name of the model is Nucleotide Transformer, I wonder if you have tested the model on RNA datasets. I am well aware that it's not originally trained on RNA sequences, and there is no U in the vocab. However, if we simply change 'U' to 'T', how it would be?
Bests,
Ai

**Comment by dallatt** [comment]
Hello @vuhongai ,

Unfortunately we have never tested this setting so I cannot really help you here! 

Best regards,

Hugo
