### ISSUE TITLE
Fine-tune models availability 

### ISSUE THREAD

**Issue by luciabarb** [instadeepai/nucleotide-transformer#3]
Hi!

Are the fine-tuned models going to be available at some point?

Thanks!!

**Comment by dallatt** [comment]
Hello,

I apologize for the late reply.

We have released notebooks to present how to replicate our results and finetune our various models, that you can find at InstaDeep's [space](https://huggingface.co/InstaDeepAI), [with](https://github.com/huggingface/notebooks/blob/main/examples/nucleotide_transformer_dna_sequence_modelling_with_peft.ipynb) and [without](https://github.com/huggingface/notebooks/blob/main/examples/nucleotide_transformer_dna_sequence_modelling.ipynb) Parameter Efficient Finetuning !
