### ISSUE TITLE
NT nucleotide-level splice site prediction

### ISSUE THREAD

**Issue by pabloacera** [instadeepai/nucleotide-transformer#41]
Hi, 
Thank you for sharing your paper and code! I was wondering if you are planning on making available the code for the NT fine-tuned for nucleotide-level splice site prediction featured in Figure 5d.
Thank you so much for considering my request!

**Comment by dallatt** [comment]
Hello, 

I suggest you check out the SegmentNT model that we just released, where you can not only predict splice sites acceptor and donor, but a set of 12 other genomic features for each input nucleotides!

Best,
Hugo
