### ISSUE TITLE
Training process for Nucleotide Transformer Model

### ISSUE THREAD

**Issue by ghost** [instadeepai/nucleotide-transformer#42]
Thank you for sharing Nucleotide Transformer! I am trying to analyze RNA sequences using a custom dataset that is not compatible with the available pretrained models. I would like to train the model on my own dataset for a classification task, however I am having trouble implementing a training loop that is compatible with Nucleotide Transformer. Is it possible to expand the codebase to include examples of your training procedures and implemented metrics, etc. so a new pretrained model may be built?

**Comment by dallatt** [comment]
Hello, 

If you plan on finetuning one of the models on your custom dataset (or even training from scratch), I suggest you look at the HuggingFace [notebooks](https://github.com/instadeepai/nucleotide-transformer?tab=readme-ov-file#huggingface-) we made available. 

Best regards,

Hugo
