### ISSUE TITLE
Checkpoints are not downloading.

### ISSUE THREAD

**Issue by princethewinner** [instadeepai/nucleotide-transformer#43]
I am trying the example notebook from the repository but my code is stuck at the `get_pretrained_model` call.

![image](https://github.com/instadeepai/nucleotide-transformer/assets/5406384/c580d044-1708-4468-80a1-90ade156f2aa)

**Comment by dallatt** [comment]
Hello @princethewinner,

This is new and comes from interactions between `tqdm` and `jupyter notebook`. You can bypass it by disabling `tqdm`, or I have just added a `verbose` argument which when set to `False` will dot display a progress bar and therefore not trigger the problem.

Best,
Hug
