### ISSUE TITLE
v2 checkpoints for TensorFlow

### ISSUE THREAD

**Issue by felbecker** [instadeepai/nucleotide-transformer#44]
Hi,

thank you for your incredible work!

How much work would it be to generate model checkpoints for your updated v2 models that can be loaded and finetuned in TensorFlow and do you, by chance, have plans to support TensorFlow in the future?

Best,
Felix

**Comment by dallatt** [comment]
Hello @felbecker ,

HuggingFace automatically converts the models to tensorflow safetensors. We just updated the repositories with them, you can find one of the v2 model's tensorflow version [here](https://huggingface.co/InstaDeepAI/nucleotide-transformer-v2-500m-multi-species/blob/main/model.safetensors).

Best regards,

Hugo

**Comment by felbecker** [comment]
Great, thanks!
