### ISSUE TITLE
Cannot download the pre-training weight

### ISSUE THREAD

**Issue by HelloWorldLTY** [instadeepai/nucleotide-transformer#59]
Thanks for your work. It seems that we cannot download the pre-training weights with the example codes:

```
/home/tl688/.cache/nucleotide_transformer/1B_agro_nt/hyperparams.json: 100%|██████████| 1.24k/1.24k [00:00<00:00, 6.99kB/s]
/home/tl688/.cache/nucleotide_transformer/1B_agro_nt/ckpt.joblib:   0%|          | 0.00/3.97G [00:00<?, ?B/s]
```

The second process does not change for a long time. Thanks a lot.

**Comment by dallatt** [comment]
Hello @HelloWorldLTY ,

This comes from interactions between `tqdm` and `jupyter` notebook. You can bypass it by disabling `tqdm,` or I have just added a verbose argument to `get_pretrained_model` which when set to `False` will dot display a progress bar and therefore not trigger the problem.

Best,
Hugo

**Comment by HelloWorldLTY** [comment]
Hi, I think it is not a problem of displayment. I have cheked that the job lib file is always 0:

<img width="1233" alt="image" src="https://github.com/instadeepai/nucleotide-transformer/assets/43333475/980c8fec-3720-4a7b-9df1-8b8739c8550c">

Is it possible to be resolved by setting the false argument? Thanks.
