### ISSUE TITLE
how to deal with the seq position of reference genome?

### ISSUE THREAD

**Issue by zzzseeu** [instadeepai/nucleotide-transformer#63]
Hi dallatt,

Thanks for your work and providing such a great tool. 

I would like to know how you process the sequence position information of the reference genome. I saw in the article that during the data preparation stage, the mutation sequence in the individual from corresponding position was used to replace the tokens of the reference seq. I don't know how this step is implemented because I don't see the input related to position information in your codes. 

![image](https://github.com/instadeepai/nucleotide-transformer/assets/45264835/c7685984-10c3-41bb-a5ac-7bfa1594d4d4)

Looking forward to your reply, thanks!

**Comment by dallatt** [comment]
Hello @zzzseeu , 

This replacement of the tokens is done offline, outside of the model. During the training, a given sequence is sampled from the reference genome and we modify it with the given mutation before tokenizing, and the resulting tokens are fed to the model.

Hope this helps!
Hugo
