### ISSUE TITLE
how to get the segmentation dataset of genomics elements

### ISSUE THREAD

**Issue by lightyisu** [instadeepai/nucleotide-transformer#67]
hi,thanks to your work!
I read the paper SegmentNT and found this great idea of using unet to reach single-nucleotide resoltion.
I notice to train SegmentNT you curated a dataset of annotations at nucleotide-level precision for 14 types of
genomic elements.
May i ask Is it possible to get this segmentation dataset of genomics elements at nucleotide-level directly?

**Comment by dallatt** [comment]
Hello @JasonLinjc ,

Can you please send an email to the corresponding authors so that we can better assist you on this?

Best regards,
Hugo
