### ISSUE TITLE
Zero Shot Data? 

### ISSUE THREAD

**Issue by fma231** [instadeepai/nucleotide-transformer#69]
Hello 

I am wondering if you could please provide one of the datasets used in predicting mutation effect during zero-shot inference. The paper mentions the use of ensembl variant effect predictor to get the corresponding effect of variants, but could you please provide the sequences used as those variants. 

Thank you

**Comment by JavierMenRev** [comment]
Hi @fma231 , 
The FASTA files are quite big, but if you have a set of annotated variants by VEP you can run [VCF2FASTA](https://github.com/JavierMenRev/VCF2FASTA) to get the sequences. Note that for our study we ONLY used SNPs and each sequence had a length of 6kb. 
Let me know if this helps.
Javier
