### ISSUE TITLE
Detection Threshold(s) for SegmentNT

### ISSUE THREAD

**Issue by zsewa** [instadeepai/nucleotide-transformer#79]
Dear SegmentNT team,

It would be great if you could clarify something about the detection threshold for SegmentNT.
Which value is used as this threshold? Is it just, e.g., 0.5 for all the features, or do you use other thresholds?

Thanks!

**Comment by dallatt** [comment]
Hello @zsewa ,
We use the the same threshold for all features: 0.5 :)
